const MyProjects = [
  {
    id: 1,
    urlimage: "../project-8.png",
    typeProject: "website",
    title: "EduPress",
    date: "20/03/2025",
    desc: "EduPress is a dynamic online learning platform offering a variety of professional courses. It provides users with an easy-to-navigate platform, interactive features, and a wide range of courses for personal and professional growth.",
    basicLanguages: "HTML-CSS-JS",
    frameworks: "TailwindCSS",
    libraries: "React",
    tools: "HTML-CSS-JS-TailwindCSS-React",
    demo: "https://edupress-react-app.netlify.app/",
    github: "https://github.com/mohammed-ismaeel/Edupress",
    gallery: ["../project-8.png", "../project-8.png", "../project-8.png"],
  },
  {
    id: 2,
    urlimage: "../project-3.png",
    typeProject: "website",
    title: "B-World",
    date: "25/11/2024",
    desc: "B-world is an innovative and user-centric online platform designed for book lovers. It allows users to browse, review, and purchase books from a vast collection, with advanced search filters, personalized recommendations, and social features.",
    basicLanguages: "HTML-CSS-JS",
    frameworks: "React, TailwindCSS",
    libraries: "",
    tools: "HTML-CSS-JS-React-TailwindCSS",
    demo: "https://mohammed-ismaeel.github.io/Task5_Books/",
    github: "https://github.com/mohammed-ismaeel/Task5_Books",
    gallery: [
      "../project-3.png",
      "../project-3-4.png",
      "../project-3-5.png",
      "../project-3-6.png",
    ],
  },
  {
    id: 3,
    urlimage: "../project-1.png",
    typeProject: "website",
    title: "RentUp",
    date: "12/10/2024",
    desc: "RentUP is a modern and user-centric real estate website designed to help users find their next home with ease. It offers a wide range of features, including detailed property listings, easy navigation, and a streamlined process for booking and viewing properties.",
    basicLanguages: "HTML-CSS",
    frameworks: "",
    libraries: "",
    tools: "HTML-CSS",
    demo: "https://mohammed-ismaeel.github.io/RentUp/",
    github: "https://github.com/mohammed-ismaeel/RentUp",
    gallery: [
      "../project-1.png",
      "../project-1-1.png",
      "../project-1-2.png",
      "../project-1-3.png",
    ],
  },
  {
    id: 4,
    urlimage: "../project-2.png",
    typeProject: "website",
    title: "K2skiing",
    date: "03/01/2025",
    desc: "K2skiing is a dynamic and visually engaging website designed for ski enthusiasts. It showcases the best ski destinations, gear reviews, and tips for beginners. The platform is optimized for both beginners and experienced skiers, providing an immersive experience.",
    basicLanguages: "HTML-CSS",
    frameworks: "",
    libraries: "",
    tools: "HTML-CSS",
    demo: "",
    github: "",
    gallery: [
      "../project-2.png",
      "../project-2-1.png",
      "../project-2-2.png",
      "../project-2-3.png",
    ],
  },

  {
    id: 5,
    urlimage: "../project-4.png",
    typeProject: "website",
    title: "Furniture",
    date: "07/11/2024",
    desc: "Furniture is a sleek and innovative website designed to provide users with the best shopping experience. The site features detailed product listings, smooth navigation, and a powerful filtering system for easy shopping.",
    basicLanguages: "HTML-CSS-JS",
    frameworks: "",
    libraries: "",
    tools: "HTML-CSS-JS",
    demo: "https://mohammed-ismaeel.github.io/Furniture/",
    github: "https://github.com/mohammed-ismaeel/Furniture",
    gallery: ["../project-4.png"],
  },
  {
    id: 6,
    urlimage: "../project-5.png",
    typeProject: "website",
    title: "Organick",
    date: "14/02/2024",
    desc: "Organick is a clean and vibrant website designed for health-conscious consumers seeking organic products. It features detailed product descriptions, user-friendly navigation, and an efficient shopping cart system for easy purchases.",
    basicLanguages: "HTML-CSS-JS",
    frameworks: "",
    libraries: "",
    tools: "HTML-CSS-JS",
    demo: "https://mohammed-ismaeel.github.io/Organick/",
    github: "https://github.com/mohammed-ismaeel/Organick",
    gallery: [
      "../project-5.png",
      "../project-5-1.png",
      "../project-5-2.png",
      "../project-5-3.png",
      "../project-5-4.png",
      "../project-5-5.png",
    ],
  },
  {
    id: 7,
    urlimage: "../project-6.png",
    typeProject: "website",
    title: "Travel Agency",
    date: "22/09/2024",
    desc: "Travel is a visually engaging website designed for travelers seeking exceptional tour packages. The platform offers a wide range of travel options, personalized packages, and detailed itineraries to cater to every traveler’s needs.",
    basicLanguages: "HTML-CSS-JS",
    frameworks: "",
    libraries: "",
    tools: "HTML-CSS-JS",
    demo: "https://travel-react-new-app.netlify.app/",
    github: "https://github.com/mohammed-ismaeel/Travel-React.js",
    gallery: ["../project-6.png", "../project-6-2.png", "../project-6-3.png"],
  }
];

export default MyProjects;
